spring:
  main:
    banner-mode: "off"
    log-startup-info: "false"
  app:
    version: 0.0.1

  application:
    name: "tdd_jdbctemplate"

profiles:
  active: local

spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://localhost:5432/test
spring.datasource.username: postgres
spring.datasource.password: postgres